version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: always

  sdk:
    image: schedule-development-kit-backend
    build:
      context: .
      dockerfile: src/ScheduleDevelopmentKit.Api/Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:80"
    networks:
      - postgres
    environment:
      DB_CONNECTION_STRING: "host=postgres;port=5432;database=ScheduleDkDb;username=postgres;password=changeme"

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: